### ISSUE TITLE
Add multi categories 

### ISSUE THREAD

**Issue by phantomhell** [christophery/proton#4]
Please add multi categories on top of the article, if users add multiple categories.

Add multiple categories
![Screenshot 2024-06-13 06 30 02](https://github.com/christophery/proton/assets/2301224/9a39aaad-51a0-4f09-9737-658b15ade4de)

Article on the frontend
![Screenshot 2024-06-13 06 30 18](https://github.com/christophery/proton/assets/2301224/5fc37edd-b81b-438c-accf-36851a6487c5)

**Comment by christophery** [comment]
Thanks for your suggestion.

**This is how it will work:** all categories will be displayed only on the post/article pages, but only the first category will be displayed on the index pages (this is how it functions currently).

**Comment by christophery** [comment]
This was added in [version 1.0.2](https://github.com/christophery/proton/releases/tag/1.0.2).

**Comment by phantomhell** [comment]
Thanks for add multi categories feature. It's awesome
![Screenshot 2024-06-17 08 42 11](https://github.com/christophery/proton/assets/2301224/72958a70-9281-4c99-80d6-abbe16d777ec)
