### ISSUE TITLE
No tag list at the bottom

### ISSUE THREAD

**Issue by phantomhell** [christophery/proton#5]
No tags list at the bottom
![Screenshot 2024-06-13 06 32 14](https://github.com/christophery/proton/assets/2301224/a47b1fd2-988d-4eab-ab23-7aac8d558a72)

**Comment by christophery** [comment]
Hi,

This feature will not be added but might be reconsidered in the future.

In the meantime, you can [add a post tags block](https://wordpress.org/documentation/article/post-tags-block/) to a post in order to get this functionality.

Cheers.
