### ISSUE TITLE
How to fix overlapped menu

### ISSUE THREAD

**Issue by phantomhell** [christophery/proton#7]
I have auto ads which is injected at header, but it has been overlapped the menu (only at homepage), no problem at other page (single post, single page or archive).
![1](https://github.com/christophery/proton/assets/2301224/6c2785c8-84fc-4568-b71a-b0e35d309eef)

Any suggestion to fix this issue?

**Comment by christophery** [comment]
Good catch! This bug would also occur if a user enabled the [toolbar](https://wordpress.org/documentation/article/toolbar/).

This will be resolved in the next release of the theme but if you want to fix it immediately you can add the `position: relative` property to the `.viewport` CSS class. This custom CSS can be added under [Appearance > Customize > Additional CSS](https://wordpress.org/documentation/article/customizer/#additional-css).
